name: dotnet package

on:
  push:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: dotnet publish --configuration Release
      - name: Test
        run: dotnet test
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          retention-days: 7
          name: JAngine-bin
          path: JAngine.All/bin/Release/net7.0/publish/*
  
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Pack
        run: dotnet pack --configuration Release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          retention-days: 7
          name: JAngine-nupkg
          path: ./**/*.nupkg
          
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
      - uses: actions/download-artifact@v3
        with:
          name: JAngine-nupkg
          path: ./
      - name: Publish NuGet package
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "./" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }