name: Upload dotnet package

on:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          source-url: https://nuget.pkg.github.com/<owner>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release JAngine.All
      - name: Create the package
        run: dotnet pack --configuration Release JAngine.All
      - name: Publish the package to GPR
        run: dotnet nuget push JAngine.All/bin/Release/*.nupkg